name: Todo 🚧

on:
    push:
        branches:
            - main
            - dev

jobs:
    todo:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: TODO to Issue
              uses: alstr/todo-to-issue-action@v4.6.8
              id: todo
